version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5050:8080"
    depends_on:
      - mysql
      - mongo
    entrypoint: go run server.go
    restart: always
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ian123
      - MYSQL_ROOT_USER=root
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      
    