application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  uploadPath: "./youwannaput"

mysql:
  host: 127.0.0.1
  port: 3306
  username: "who"
  password: "idk"
  dbname: "thisisexample"

mongo:
  host: 127.0.0.1
  port: 27017
  database: "Test"

JWT:
  secret: "putsomethingcomplex"

Log:
  logPath: "/log"
  logFile: "_ginError.log"
   