application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  uploadPath: "./upload"
  mode: "debug"

mysql:
  host: 127.0.0.1
  port: 3306
  username: "root"
  password: "ian123"
  dbname: "thisistest"
  maxIdle: 10
  maxConn: 100
  connMaxLifetime: 30

mongo:
  host: 127.0.0.1
  port: 3307
  database: "Test"

JWT:
  secret: "thisistestanyway"

Log:
  logPath: "/log"
  logFile: "_ginError.log"
   